### ISSUE TITLE
Update README to match template

### ISSUE THREAD

**Issue by maxveldink** [open-feature/ruby-sdk#120]
There is an [OF README template](https://github.com/open-feature/.github/tree/main/templates/READMEs) that we should be using for the Ruby gem.

**Comment by beeme1mr** [comment]
We should verify if there are any markdown limitations when publishing Ruby gems. We ran into a few issues with NuGet and ended up creating an alternative readme template.

**Comment by maxveldink** [comment]
We also have a test that executes the examples from the README. We should continue to have that work.
