### ISSUE TITLE
Auto-merge merges before CI finishes

### ISSUE THREAD

**Issue by technicalpickles** [open-feature/ruby-sdk#39]
@josecolella and I saw this yesterday. It's a workflow we use during work of enabling auto-merge, so it will land when someone approves it.

Two places it didn't work as expected:
- https://github.com/open-feature/ruby-sdk/pull/38
- https://github.com/open-feature/ruby-sdk/pull/34

I _think_ the fix is to make sure branch protections are on for requiring Status. While pairing with @josecolella on https://github.com/open-feature/ruby-sdk/pull/34 we added the CI jobs, but unfortunately, the names have the ruby version encoded in them, which means it will change anytime Ruby version or the OS matrix changes.

In https://github.com/open-feature/ruby-sdk/pull/38 I added a CI Status job that waits on everything else, which should do it. I think we just now need to updated to remove the old ones, and add CI Status to it.

Someone with admin on the repo would need to do that, as I don't currently have it.

**Comment by beeme1mr** [comment]
@technicalpickles I've updated the branch protection. I'll leave the issue open until I get confirmation that it worked.

**Comment by beeme1mr** [comment]
Sorry, it should be working now.

**Comment by technicalpickles** [comment]
Looks better now, thanks!
