### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by mschoenlaub** [open-feature/ruby-sdk#54]
Not sure where we are at, so we need to measure it. But I don't think we are anywhere near an acceptable threshold, less so for the current version of the spec.

**Comment by technicalpickles** [comment]
https://github.com/open-feature/ruby-sdk/pull/59 landed, so we are collecting data now. Here's the first report with it enabled: https://github.com/open-feature/ruby-sdk/pull/60#issuecomment-1716282259

![CleanShot 2023-09-12 at 16 34 49](https://github.com/open-feature/ruby-sdk/assets/159/6f75afb4-5147-4411-81af-864848504249)

[link](https://app.codecov.io/gh/open-feature/ruby-sdk)

At 98%, I think we are pretty good. I'm more inclined to worry about the level of coverage when more of the spec is implemented rather worry too much right now.
