### ISSUE TITLE
Requirements for Release

### ISSUE THREAD

**Issue by josecolella** [open-feature/ruby-sdk#7]
https://github.com/open-feature/openfeature-ruby/issues/7#tasklist-block-f1d814c4-40b3-4844-8737-35cd0b2ed007

**Comment by maxveldink** [comment]
We've done a few releases so far, and [are listed](https://openfeature.dev/ecosystem?instant_search%5BrefinementList%5D%5Btechnology%5D%5B0%5D=Ruby) on the OF website now. Closing this as I believe we've fulfilled the scope here
